const express = require('express')
const app = express()
const cors = require('cors')
const jwtAuthorization = require('./src/middleware/jwtAuth')
const userAuthentication = require('./src/middleware/userAuth')
const productValidation = require('./src/validations/validators/productValidation')
const statusValidation = require('./src/validations/validators/statusValidation')
const updateValidation = require('./src/validations/validators/updateValidation')
const sellProductValidation = require('./src/validations/validators/sellProductValidation')
const adminDetailsRoute = require('./src/routes/adminDetails')
const createProductRoute = require('./src/routes/createProduct')
const verifyProductRoute = require('./src/routes/verifyProduct')
const updateProductRoute = require('./src/routes/updateProduct')
const showProductsRoute = require('./src/routes/showProducts')
const sellProductRoute = require('./src/routes/sellProduct')
const loginRoute = require('./src/routes/login')
const registerRoute = require('./src/routes/registerUser')
app.use(express.json())
app.use(cors())
app.use('/adminDetails',adminDetailsRoute)
app.use('/registerUser',registerRoute)
app.use('/login',userAuthentication,loginRoute)
app.use('/createAndTransferProduct',jwtAuthorization,productValidation,createProductRoute)
app.use('/verifyAndTransferProduct',jwtAuthorization,statusValidation,verifyProductRoute)
app.use('/updateAndTransferProduct',jwtAuthorization,updateValidation,updateProductRoute)
app.use('/showProducts',jwtAuthorization,showProductsRoute)
app.use('/sellProduct',jwtAuthorization,sellProductValidation,sellProductRoute)


app.listen(5000,()=>{
    console.log("Server is listening on PORT 5000")
})  